{% set name = "et_xmlfile" %}
{% set version = "2.0.0" %}
{% set short_version = version.rsplit('.', 1)[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: dab3f4764309081ce75662649be815c4c9081e88f0837825f90fd28317d4da54

  - url: https://foss.heptapod.net/openpyxl/{{ name }}/-/archive/branch/{{ short_version }}/{{ name }}-branch-{{ short_version }}.tar.gz
    sha256: 6ad4c0d6c8e5f8a2bae8bbfcf69ead4b33c8628dfb3d0a0dac340f3289c244f0
    folder: gh_src

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  source_files:
    - gh_src/et_xmlfile/tests
  imports:
    - et_xmlfile
    - et_xmlfile.incremental_tree
    - et_xmlfile.xmlfile
  requires:
    - pip
    - pytest
    - lxml
  commands:
    - pip check
    - python -c 'from importlib.metadata import version; assert version("{{ name }}") == "{{ version }}"'
    - python -c "import os,shutil,sysconfig; sp=sysconfig.get_paths().get('purelib') or sysconfig.get_paths().get('platlib'); src=os.path.join('gh_src','et_xmlfile','tests'); dst=os.path.join(sp,'et_xmlfile','tests'); os.makedirs(os.path.dirname(dst), exist_ok=True); shutil.copytree(src, dst, dirs_exist_ok=True)"
    - PYTHONPATH=$SRC_DIR/gh_src pytest gh_src -l --strict-markers --ignore=gh_src/et_xmlfile/tests/_vendor  # [unix]
    - set PYTHONPATH=%SRC_DIR%\gh_src && pytest gh_src -l --strict-markers --ignore=gh_src/et_xmlfile/tests/_vendor  # [win]

about:
  home: https://foss.heptapod.net/openpyxl/et_xmlfile
  license: MIT AND PSF-2.0
  license_family: MIT
  license_file: LICENCE.rst
  summary: An implementation of lxml.xmlfile for the standard library
  description: |
    et_xmlfile is a low memory library for creating large XML files
  doc_url: https://et-xmlfile.readthedocs.io
  dev_url: https://foss.heptapod.net/openpyxl/et_xmlfile

extra:
  recipe-maintainers:
    - curtisalexander
