appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cQd6YJ70DSK4hXwHm0o+dUW3Kf6boF7TfX0HBu3mIeE8WpW0AhwzGU5LV8MZLDArq43rlHobq5mMK/lAeIbjZJPSrwKXp2LtAmrEw01R/b/qd09DY4JBLmA5Z7tfaev+x50rTWMI8gXEBBQ6iC+RSf7VGp5n77O9qog+9qCeldYMbhO6sjEdi6tiWclc/qnc4eleUly+3qWaNvXJ1jWcnw9RQZB75tUQFS7X+FKG/ThG5FTS4AuISV9p222gU0+3qN58IJgKMHHWP/KonrMtIRkvDvD149i32QKZvLxZ5Io/eNOrqlFAdAy8ShrNtIYpKb0exAW8y8WObXHprjqDXxoM1U/CPFsWFNln6pgFTQLZdyBdpSXY7boDOq737CooRTJ2/z7AhBead9c2b9+IQFKb0A+xprWqUzXF2hx5X50FsoA/kobpTHPd4/iSI2YSmATUo04eQpZlh90cwJkruB/vIbCb6SyLphStNQChAmsdUInkQlTK8yWaSDVGuHypGnO5L/QmkxUkUsfY/4A+aQkEZ8yLMNvPDwq+LjGF/AqyuQqVW0tf36RNnTKz/FrsEf7Kl7Cd/jcs2jqkJl3kvrmjFUy/TRRtA4k69O4VJjDJFsrXhLfshm1kFYyLXstUB8aMbx/JmE9B4mjL3LQGAUNVPZ6Pq8XnfeO4qriZETQ=}
provider:
  win: azure
conda_forge_output_validation: true
