travis:
  secure:
    BINSTAR_TOKEN: YHUkEXGIy8RYYfdIxJCfNc6BrCtTQ3QEaCYcy0xnetJ2WXWj87Wkv9SKJEd+uFN9WHN2rnpsbIGI2gUIczmf68BWX1qtC/OZ6rGruvohFe7rzXZIZ9kjcn36uUUiZ/QbEdDLHk/nA/o2lOSAheIfyrH4Eo+NcOZBmWBRAUG1sclHde5T3Gr03/J6oQf+lSMVQo4ceV5jTDNlXm1khO9EWrqc2lDla1pkFeRKx+gGqapAMR2C8MnrkxnWoZZu9uAsF9fNMpUSzUuJHFhnO/YY7NkhMA0gLB/KZVz35GDyWbl2uhzKj0KB347rbTDkEdYdXofE0uvDtfXXiDjU8azgMyqHcPH94R3gaPBRecoUE9YqyEuSvXJTHYN8ZHc0yjTWWbw82oGIPB0Rt4Bk/Q0iao4CAYbyWhfHMpgY663NDPm1knusyoY4LMCuDAYMfCVqGGPYEt1JYsGTd/WfjjJrqHjcNQ4EgdabE1DrfDkU9xw3IrYc1AiC1c4X4WNClin37Wx/LfdTLxcD3ZbNdBbX/6bB12vwZY1bijfzip6WR8a6pIds2+i6mEbPQG4u2gx0q9ufmA58OABSmESPUnbczfwwDxW6h7Xk/bAsA0ZL79UcowUXWZjLP40QmWdx05cbywxl8iwF9jHNZ7+u43u5BYYhS0P7dYDfH8fl1gxWdQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
